CREATE TABLE IF NOT EXISTS singers (
`singer_id` INT UNSIGNED AUTO_INCREMENT NOT NULL,
`name` VARCHAR (100) NOT NULL UNIQUE,
`country` VARCHAR (100) NOT NULL,
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (singer_id)
)DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_UNICODE_CI;

CREATE TABLE IF NOT EXISTS albums  (
`album_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`singer_id` INT UNSIGNED NOT NULL,
`title` VARCHAR(100) NOT NULL UNIQUE,
`year` INT NOT NULL,
`musical_genre` VARCHAR(50) NOT NULL,
`cover_url` VARCHAR(500) DEFAULT NULL,
`price` DOUBLE(6,2) DEFAULT NULL,
`stock` INT NOT NULL DEFAULT '0',
`description` TEXT,
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (`album_id`),
FOREIGN KEY (`singer_id`) REFERENCES `singers` (`singer_id`)
)DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_UNICODE_CI;

CREATE TABLE IF NOT EXISTS customers (
`customer_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`name` VARCHAR(50) NOT NULL,
`email` VARCHAR(100) NOT NULL UNIQUE,
`birthdate` DATE DEFAULT NULL,
`gender` ENUM('M','F') DEFAULT NULL,
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (`customer_id`)
)DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_UNICODE_CI;

CREATE TABLE IF NOT EXISTS transactions (
`transaction_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`album_id` INT UNSIGNED NOT NULL,
`customer_id` INT UNSIGNED NOT NULL,
`type` ENUM('Purchase', 'Rental') NOT NULL,
`start_date` DATE DEFAULT NULL,
`end_date` DATE DEFAULT NULL,
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (`transaction_id`),
FOREIGN KEY (`album_id`) REFERENCES `albums` (`album_id`),
FOREIGN KEY (`customer_id`) REFERENCES `customers` (`customer_id`)
)DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_UNICODE_CI;

